name: furniture_app_ui
description: An ecommerce app ui for furniture purchase.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  assets:
     - assets/icons/arrow-long-left.svg
     - assets/icons/bag.svg
     - assets/icons/check.svg
     - assets/icons/home.svg
     - assets/icons/menu.svg
     - assets/icons/ripple.gif
     - assets/icons/scan.svg
     - assets/icons/search.svg
     - assets/icons/user.svg
     - assets/icons/spinner.gif
     - assets/category/cabinet_bkg.jpg
     - assets/category/cabinet.png
     - assets/category/home_deco.png
     - assets/category/home_deco_bkg.jpg
     - assets/category/light_bkg.jpg
     - assets/category/light.png
     - assets/category/sofa_bkg.jpg
     - assets/category/sofa.png
     - assets/category/table_bkg.jpg
     - assets/category/table.png





   



  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  
